server:
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:localhost.p12
#    key-store-password: changeit
#    key-store-type: PKCS12

spring:
  config:
    import:
      - classpath:application-domain.yaml
      - classpath:application-infra.yaml

jwt:
  secret: ${SECRET}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}