spring:
  rabbitmq:
    addresses: ${CLOUDAMQP_URL}
    connection-timeout: 5000

coolsms:
  url: https://api.coolsms.co.kr
  apiKey: ${COOLSMS_API_KEY}
  secretKey: ${COOLSMS_SECRET_KEY}
  from: ${COOLSMS_FROM}

verification-code:
  expiration: ${VERIFICATION_CODE_EXPIRATION}

verified-token:
  expiration: ${VERIFIED_TOKEN_EXPIRATION}

kakao:
  api-key: ${KAKAO_API_KEY}
  geocoding-url: https://dapi.kakao.com

supabase:
  url: ${SUPABASE_URL}
  api-key: ${SUPABASE_API_KEY}
  storage:
    bucket:
      rental-item-images: rental-item-images
      user-profile-images: user-profile-images

outbox:
  poll-interval-ms: 5000
  cleanup-older-than-hours: 1
  max-retry-count: 5

chat:
  exchange-name: chat.broadcast
