spring:
  datasource:
    url: ${DATASOURCE_URL}
    hikari:
      data-source-properties:
        prepareThreshold: 0
  jpa:
    open-in-view: false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: validate

  data:
    redis:
      url: ${UPSTASH_REDIS_URL}
      username: default
      password: ${UPSTASH_REDIS_TOKEN}