spring:
  application:
    name: backend-kotlin

  datasource:
    url: ${DATASOURCE_URL}
    hikari:
      data-source-properties:
        prepareThreshold: 0
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    hibernate:
      ddl-auto: update

  data:
    redis:
      url: ${UPSTASH_REDIS_URL}
      username: default
      password: ${UPSTASH_REDIS_TOKEN}

coolsms:
  url: https://api.coolsms.co.kr
  apiKey: ${COOLSMS_API_KEY}
  secretKey: ${COOLSMS_SECRET_KEY}
  from: ${COOLSMS_FROM}

verification-code:
  expiration: 5

verified-token:
  expiration: 5

jwt:
  secret: ${SECRET}
  access-token-expiration:
    milliseconds: 1800000
    seconds: 1800
  refresh-token-expiration:
    milliseconds: 604800000
    seconds: 604800

kakao:
  api-key: ${KAKAO_API_KEY}
  geocoding-url: https://dapi.kakao.com