spring:
  application:
    name: backend

  datasource:
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: https://endless-kitten-6997.upstash.io
      port: 6379
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

coolsms:
  url: https://api.coolsms.co.kr
  apiKey: ${COOLSMS_API_KEY}
  secretKey: ${COOLSMS_SECRET_KEY}
  from: ${COOLSMS_FROM}