spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?user=postgres.jeenwjbvzjvbpmpllepp&password=eornjs1449.
  jpa:
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: https://endless-kitten-6997.upstash.io
      port: 6379
      password:
      ssl: true

coolsms:
  url: https://api.coolsms.co.kr
  apiKey:
  secretKey:
  from: 01046244800